data <- read.table(file = "C:/Users/S.kh/Desktop/Coursera/Exploratory project/household_power_consumption.txt",header = TRUE, sep = ";", na.strings = "?")
data <- data[data$Date %in% c("1/2/2007", "2/2/2007"), ]
x <- paste(data$Date, data$Time, sep = " ")
datetime <- strptime(x, "%d/%m/%Y %H:%M:%S")
data <- cbind(data, datetime)
plot(data$Sub_metering_1~ data$datetime, type = "l", xlab = "", ylab = "Energy Sub Metering")
lines(data$Sub_metering_2~data$datetime, col = "red")
lines(data$Sub_metering_3~data$datetime, col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = 1)
dev.copy(png, file = "plot3.png", width = 480, height= 480)
dev.off()